// Column configuration for contacts table
export const CONTACTS_TABLE_DEFAULT_COLUMNS = [
  {
    label: "Select",
    accessor: "_id",
    visible: true,
    order: 0,
    width: "48px",
  },
  {
    label: "Name",
    accessor: "name",
    visible: true,
    order: 1,
    width: "250px",
  },
  {
    label: "Email",
    accessor: "email",
    visible: true,
    order: 2,
    width: "250px",
  },
  {
    label: "Phone",
    accessor: "phoneNumber",
    visible: true,
    order: 3,
    width: "180px",
  },
  {
    label: "Status",
    accessor: "status",
    visible: true,
    order: 4,
    width: "150px",
  },
  {
    label: "Assigned To",
    accessor: "assignedTo",
    visible: true,
    order: 5,
    width: "200px",
  },
  {
    label: "Source",
    accessor: "source",
    visible: true,
    order: 6,
    width: "150px",
  },
  {
    label: "Company",
    accessor: "company",
    visible: true,
    order: 6.5,
    width: "180px",
  },
  {
    label: "Campaign",
    accessor: "campaign",
    visible: true,
    order: 7,
    width: "150px",
  },
  {
    label: "Project",
    accessor: "project",
    visible: true,
    order: 8,
    width: "150px",
  },
  {
    label: "Date",
    accessor: "dateInscription",
    visible: true,
    order: 9,
    width: "120px",
  },
  {
    label: "WhatsApp",
    accessor: "whatsapp",
    visible: true,
    order: 10,
    width: "100px",
  },
];
